# Generated by Django 4.2.10 on 2024-03-17 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='honorcodeviolation',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='violation_files/'),
        ),
    ]
