# Generated by Django 4.2.10 on 2024-03-20 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_honorcodeviolation_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='honorcodeviolation',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('in_progress', 'In Progress'), ('resolved', 'Resolved')], default='new', max_length=20),
        ),
    ]
