# Generated by Django 4.2.10 on 2024-03-20 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_honorcodeviolation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='honorcodeviolation',
            name='resolution_notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
