# Generated by Django 4.2.10 on 2024-03-30 05:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("mainapp", "0004_honorcodeviolation_resolution_notes"),
    ]

    operations = [
        migrations.AddField(
            model_name="honorcodeviolation",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="violations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
